### ISSUE TITLE
Blank black screen using new 2.0 ISO - blinking cursor - `libabsl_log_internal_check_op.so.2565.0.0: cannot open shared file`

### ISSUE THREAD

**Issue by ironicbadger** [basecamp/omarchy#1150]
Fresh ISO install tonight with Omarchy 2.0 on a Thinkpad X240. Hyprland failed start and I was presented with a blank black screen with a blinking cursor visible. I changed TTYs and was able to find an error using `journalctl -xe`.

```
libabsl_log_internal_check_op.so.2565.0.0: cannot open shared object file
```

I found a somewhat related issue from May https://github.com/HyDE-Project/HyDE/issues/686 which led me to try `pacman -S abseil-cpp`. After a reboot everything worked as expected.

**Comment by ironicbadger** [comment]
This also appears to be an issue launching Telegram desktop which crashes immediately when launching with `libabsl_strings.so.2508.0.0` error. 

A bit out of my area to understand why here so this comment is an FYI - I don't have a fix.

**Comment by matheuscandido** [comment]
I just had this issue installing Omarchy 2.0 iso from scratch on my desktop pc. Accessing the shell and installing abseil-cpp solved  it.

**Comment by owensd** [comment]
Same - brand new ISO install on my laptop. Adding abseil-cpp also fixed it for me.

**Comment by sknewcomb** [comment]
I also faced this issue, I found that running `ldd "$(command -v Hyprland)" | grep "not found` helped me me locate the missing library mentioned above. I did a reinstall of those libraries and did a reboot and I was good to go.

**Comment by inffy** [comment]
This seems to relate to the pacman.conf and the repo section where omarchys repo is  set in the top. This will cause issues down the line and it seems we are now "in  dependency hell" and doing partial upgrades.

**Comment by jondkinney** [comment]
I faced the same problem on a mid-2015 macbook pro. Not sure if it had anything to do with the integrated & dedicated graphics that I have or if this install was all I really needed but `sudo pacman -S abseil-cpp` got me fixed up.

![Image](https://github.com/user-attachments/assets/d524f4af-491f-4773-ae4a-a16d2a1aabc4)

**Comment by dhh** [comment]
Is this something you've noticed, @vaxerski? Saw it mentioned as a dependency to hyprutils?

**Comment by soroyv** [comment]
I just installed omarchy on a Dell laptop with the 2.0 ISO and it just stuck on the logon screen where progress bar stuck on 100%.

This was the solution for me also:
`sudo pacman -S abseil-cpp`

**Comment by ajrussellaudio** [comment]
For the benefit of anyone dropping in from Google or elsewhere, if you're looking at a completely blank screen, the command to drop to a shell is `Ctrl-Alt-F2`

Installing `abseil-cpp` worked for me too.

**Comment by krp** [comment]
Also encountered this on a fresh install of the omarchy2 iso.

For anyone new to Linux wanting to know if they're affected by this, follow @ajrussellaudio's advice (Ctrl-Alt-F2 to login) then run `journalctl | grep error` and look for a mention of libabsl not found like in the screenshot above.

There appears to be two versions of this. `omarchy/abseil-cpp 20250512.1-1` and `extra/abseil-cpp 20250814.0-1`. 

/var/cache/pacman/pkg/abseil* has both versions although /var/log/pacman.log only appears to have attempted to install 20250814 from extra.
Reinstalling the package with `sudo pacman -S abseil-cpp` installs the 20250512.1-1 version for me and then rebooting fixes the blank screen. Hyprland's looking for `/usr/lib/libabsl_log_internal_check_op.so.2505.0.0` but the 20250814 package provides `/usr/lib/libabsl_log_internal_check_op.so.2508.0.0`

**Comment by vaxerski** [comment]
> Is this something you've noticed, @vaxerski? Saw it mentioned as a dependency to hyprutils?

abseil is not a direct dep of hu, might be a dep of some dep though

**Comment by inffy** [comment]
the easiest way to fix this for now and future is to edit /etc/pacman.conf

and there in the repos part move the omarchy repo down and place it before chaotic-aur.

This way you get the correct packages from Arch repos. The absail-cpp was updated yesterday and now causes conflicts as the omarchy repo has older version.

**Comment by Tribeofhackers** [comment]
Same issue and same solution as clearly outlined by [soroyv] for us newbies - extra thank you

"This was the solution for me also:
sudo pacman -S abseil-cpp"

**Comment by dhh** [comment]
Fix the black-screen-of-death install with these steps:

1. CTRL + ALT + F2
2. Login with your credentials
3. curl -fsSL https://omarchy.org/patch/pin-abseil-cpp | bash

This has been sorted in [v2.0.2](https://github.com/basecamp/omarchy/releases/tag/v2.0.2) for new installations.

We will find the root cause and also sort out our own package repo with testing so these changes can't sneak up on us 😄

**Comment by ryanschmidt** [comment]
> Fix the black-screen-of-death install with these steps:
> 
> 1. CTRL + ALT + F2
> 2. Login with your credentials
> 3. curl -fsSL https://omarchy.org/patch/pin-abseil-cpp | bash
> 
> This has been sorted in [v2.0.2](https://github.com/basecamp/omarchy/releases/tag/v2.0.2) for new installations.
> 
> We will find the root cause and also sort out our own package repo with testing so these changes can't sneak up on us 😄

This did not fix my booting. Still loading to a black screen.

I was running yesterday when some automatic updates ran. I hadn't rebooted until last night and since then I've been unable to boot.

**Comment by dhh** [comment]
@ryanschmidt In that CTRL + ALT + F2 new TTY, share the results of these two commands:

pacman -Qi abseil-cpp
pacman -Qi uwsm

You should have abseil-cpp 20250512.1-1 and uwsm 0.23.2-1.

**Comment by ryanschmidt** [comment]
![Image](https://github.com/user-attachments/assets/5128c9f8-4248-44ee-a915-d4f97e6bee63)
![Image](https://github.com/user-attachments/assets/20a930e2-3b66-454d-ab73-b341b80bc401)

**Comment by krp** [comment]
@ryanschmidt I'd recommend checking the output of `journalctl | grep error` for the specific error mentioned in jondkinney's screenshot above, and also running `ls -al /usr/lib/libabsl*` to see if the package put the shared libraries there. Your black screen might be caused by a different issue so confirming if you're getting the same Hyprland error may help with troubleshooting it.

**Comment by ryanschmidt** [comment]
Here's the output (it's longer than the screen) of errors.

![Image](https://github.com/user-attachments/assets/e10041b2-fb80-40f3-b0a0-cbdae7abdaf4)

And the shared libraries:

![Image](https://github.com/user-attachments/assets/b439cfbe-1cde-42e3-85c3-f2b1c48c2f4e)

**Comment by dhh** [comment]
Did you restart after running the pacman command?

**Comment by ryanschmidt** [comment]
Yes. This might be relevant: https://github.com/basecamp/omarchy/issues/1151#issuecomment-3228360906

**Comment by twobuh** [comment]
I'm in a similar state as @ryanschmidt .  

I've been running Omarchy on a Framework 13 AI 300 since late July with only one hiccup (see context below) and a tremendous amount of fun!

**Possibly relevant context:**
Two weeks ago I encountered issue #693 following an update, and the proposed fix worked well for me with no deviations.
https://github.com/basecamp/omarchy/discussions/693

I updated today, and the system reboots to a black screen.  Everything looked fine after the update until I rebooted.  After the first power cycle I did see the exact same screen that I saw with issue #693 
(screenshot >>> https://discord.com/channels/1390012484194275541/1390012487000395859/1405315345429954791 )
Subsequent power cycles have placed me in a state with a pure black screen, and no cursor in the upper left corner.

**Currently:**
I am able to get to a new TTY utlizing CTRL + ALT + F2.... curl -fsSL... plus power cycles. This results in a black screen.
I have also run   `sudo pacman -Syyu`   and don't see any missing libraries.
abseil-cpp 20250814.0-1 and uwsm 0.23.2-1

**Comment by ryanschmidt** [comment]
Yes. That summarizes my issue well. I'm on a Framework 16. Things were fine until I rebooted.

Actively trying to troubleshoot it again this evening. I miss Omarchy.

**Comment by ryanschmidt** [comment]
> I also faced this issue, I found that running `ldd "$(command -v Hyprland)" | grep "not found` helped me me locate the missing library mentioned above. I did a reinstall of those libraries and did a reboot and I was good to go. 

I'm missing many libraries.

![image](https://github.com/user-attachments/assets/0288bc24-ac75-4046-81ac-021ea786c20b)

Fixed the missing libraries with sudo pacman -S abseil-cpp but still black screen of death.

**Comment by ryanschmidt** [comment]
It turned out to be an issue with some bind settings in my `monitors.conf` that Omarchy decided it didn't like anymore. https://github.com/basecamp/omarchy/issues/1210#issuecomment-3231186894

**Comment by dinvlad** [comment]
I just had this issue installing from just-downloaded ISO on a new Framework 13 (7640U).

It failed with `abseil-cpp` version `20250512.1` missing (URL was giving 404). I installed it using `sudo pacman -S abseil-cpp`, but that seems to have installed **newer** version `20250814.0-1`. Re-running `install.sh` complained about the same old version again.

So then I did `sudo pacman -S downgrade && sudo downgrade abseil-cpp`, which allowed me to downgrade the version, and finally `install.sh` was happy again (and without a reboot)!

EDIT: Oh but after logging in, it does show black screen, and reboot didn't help..
EDIT2: Dropping into console and running `sudo pacman -S abseil-cpp` did install `20250814.0-1` again, and after a reboot everything works!

**Comment by tighthead3** [comment]
This worked for me on an active install of Omarchy on laptop. FYI, I have edited the monitor config file on previous versions. Here is what I'd do 

Press and hold Ctrl + Alt + F2 to get into terminal.

Type into terminal:
sudo pacman -S abseil-cpp 

Then type: Reboot 

All back to normal with 2.0.3 version.

**Comment by OmarSkalli** [comment]
> Fix the black-screen-of-death install with these steps:
> 
> 1. CTRL + ALT + F2
> 2. Login with your credentials
> 3. curl -fsSL https://omarchy.org/patch/pin-abseil-cpp | bash
> 
> This has been sorted in [v2.0.2](https://github.com/basecamp/omarchy/releases/tag/v2.0.2) for new installations.
> 
> We will find the root cause and also sort out our own package repo with testing so these changes can't sneak up on us 😄

Similar to a few others, this didn't fix it for me. However doing `sudo pacman -S abseil-cpp` worked.

**Comment by inffy** [comment]
Come on, please move the omarchy repo lines in pacman.conf to under the Arch core and extra repos.

You are going to break peoples installs over and over again as long as that omarchy repo is higher than the Arch repos.

Manjaro already did this and has broken multiple times because of the stunts like this (trying to provide its own package repos and holding back packages). We don't really need Manjaro v2.0

**Comment by dhh** [comment]
Yeah, we're moving it after those packages. Will go out in the next release. Also rejigged the repo so it only has extra packages.

**Comment by bdx-asn** [comment]
Thx for the awesome support!

**Comment by twobuh** [comment]
I'm still stuck at a black screen after following the tips I see on Discord and gihub issues.  Any advice?  I'm fully open to doing a fresh install if that is best.

Framework 13 AI 300, working great since late July sitting at black screen after updating on Tuesday.
1. CTRL + ALT + F2 (this works)
2. login (this works)
3. curl -fsSL https://omarchy.org/patch/pin-abseil-cpp | bash (this runs, but doesn't fix this issue)
4. reboot and repeat steps 1 and 2
5. sudo pacman -S abseil-cpp (this executes but returns errors (screenshot below)
6. hyperland returns error (sceenshot below)

EDIT: I ended up doing a fresh install with the 2.0.5 ISO and it worked perfectly.  Thank you DHH & Team!

![Image](https://github.com/user-attachments/assets/d48ca86e-9827-4022-bb6d-ad5b415f089b)
