### ISSUE TITLE
broken wifi after installing 2.1.0 on framework 13

### ISSUE THREAD

**Issue by ColtonIdle** [basecamp/omarchy#1422]
I wanted to try using the new iso installer (with latest configurator https://github.com/omacom-io/omarchy-configurator). installed all within 7 minutes on my framework 13! now when i log into my machine... it looks like i have wifi (like the upper right corner looks like a full wifi status bar) but ping fails, as well as navigating to any website. not sure if anything changed in 2.1.0 but ive had 0 issues with getting wifi working in the past with omarchy (and other distros).

I'm investigating and will edit the OP as I stumble upon any new findings.

**Comment by fisika1729** [comment]
This usually happen when the DHCP lease expire for me, can you check if it's the same for you? with networkctl status command after the ping fails

**Comment by ColtonIdle** [comment]
ill try that if this happens again. like i said it seems like sudo rfkill unblock all did the trick. BUT this issue can serve as a feature request I suppose. seems like if  rfkill does block all then the wifi TUI doesn't even open up.

**Comment by fisika1729** [comment]
> ill try that if this happens again. like i said it seems like sudo rfkill unblock all did the trick. BUT this issue can serve as a feature request I suppose. seems like if rfkill does block all then the wifi TUI doesn't even open up.

my configuration was omarchy dotfiles, and sudo rfkill unblock all didn't fix it yet for me

**Comment by MikeVeerman** [comment]
I'm also running into this issue.

When the bug appears, I can no longer `ping google.com` (Destination Host Unreachable). I can, however, always switch to my phone's hotspot using `iwctl` and then `ping google.com`. When switching back to the original wifi network (or rebooting the laptop), the connectivity issue persists. 

What works for me is forgetting the original network (remove the file from `/var/lib/iwd`) and authenticating again using `iwctl`. 

That's a clumsy workaround, but it points to something being corrupted in the network configuration. 

I am also on a recent Framework 13 and Omarchy v2.1.0. 

Let's find the root cause.

**Comment by fisika1729** [comment]
> I'm also running into this issue.
> 
> When the bug appears, I can no longer `ping google.com` (Destination Host Unreachable). I can, however, always switch to my phone's hotspot using `iwctl` and then `ping google.com`. When switching back to the original wifi network (or rebooting the laptop), the connectivity issue persists.
> 
> What works for me is forgetting the original network (remove the file from `/var/lib/iwd`) and authenticating again using `iwctl`.
> 
> That's a clumsy workaround, but it points to something being corrupted in the network configuration.
> 
> I am also on a recent Framework 13 and Omarchy v2.1.0.
> 
> Let's find the root cause.

you don't have to reboot the machine, but restarting the iwd service would do the trick, also i tried restarting iwd service whenever the ping fails with little bashing, but then i changed to network manager instead of iwd

**Comment by MikeVeerman** [comment]
Just to be clear: the point I tried to make is that the issue persists when rebooting the laptop. That makes it look like an "on-drive" issue instead of an "in-memory" issue.

**Comment by fisika1729** [comment]
> Just to be clear: the point I tried to make is that the issue persists when rebooting the laptop. That makes it look like an "on-drive" issue instead of an "in-memory" issue.

ahh makes sense

**Comment by dhh** [comment]
I've seen this a few times too, although not in a while. I added Update > Hardware > Wifi to the menu. That'll trigger the rfkill trick. But maybe we should also have it restart iwd. But this is of course just a failsafe. We should find the root cause and get it fixed in the correct package.

**Comment by fisika1729** [comment]
> I've seen this a few times too, although not in a while. I added Update > Hardware > Wifi to the menu. That'll trigger the rfkill trick. But maybe we should also have it restart iwd. But this is of course just a failsafe. We should find the root cause and get it fixed in the correct package.

with the help of my friend, we figured that my machine is switching bettween 2.4ghz and 5 ghz bands which leads to disconnection in my case i'll attach the commands to check the logs, also i've tried what you have mentioned with a bash script which restarts whenever it can't ping google.com or something, which works fine.

check if that's the same case with you guys `journalctl -u wpa_supplicant --no-pager -n 1000 | curl -F 'file=@-' https://0x0.st`

**Comment by czrcbl** [comment]
@fisika1729 Tanks for tagging me on the other Issue. [1475](https://github.com/basecamp/omarchy/issues/1475)

I reconfigured my router to split the 2.4 and the 5Ghz networks and connect to the 5Ghz one. But I am still getting disconnects.

I created a smelly python script that calls `sudo rfkill unblock all` whenever pinging `google.com` fails (Timeout or connection error).
Left it running in a terminal, `sudo rfkill unblock all` was not able to reestablish the connection, I still had to manually disconcect and then reconnect to the Wifi manually. 

As another trial, I changed the network conf by:
Adding `/etc/iwd/main.conf`
```
[General]
EnableNetworkConfiguration=true

[Network]
NameResolvingService=systemd
```

And turning the DHCP off on systemd network config;
`/etc/systemd/network/20-wlan.network`
```
[Match]
Name=wl*

[Link]
RequiredForOnline=routable

[Network]
DHCP=no
MulticastDNS=yes

.
.
.
```

**Comment by fisika1729** [comment]
> @fisika1729 Tanks for tagging me on the other Issue. [1475](https://github.com/basecamp/omarchy/issues/1475)
> 
> I reconfigured my router to split the 2.4 and the 5Ghz networks and connect to the 5Ghz one. But I am still getting disconnects.
> 
> I created a smelly python script that calls `sudo rfkill unblock all` whenever pinging `google.com` fails (Timeout or connection error).
> Left it running in a terminal, `sudo rfkill unblock all` was not able to reestablish the connection, I still had to manually disconcect and then reconnect to the Wifi manually. 
> 
> As another trial, I changed the network conf by:
> Adding `/etc/iwd/main.conf`
> ```
> [General]
> EnableNetworkConfiguration=true
> 
> [Network]
> NameResolvingService=systemd
> ```
> 
> And turning the DHCP off on systemd network config;
> `/etc/systemd/network/20-wlan.network`
> ```
> [Match]
> Name=wl*
> 
> [Link]
> RequiredForOnline=routable
> 
> [Network]
> DHCP=no
> MulticastDNS=yes
> 
> .
> .
> .
> ```
> 
Did it work? Rather than using sudo rfkill unblock all use `systemctl restart iwd` or systemctl restart `Network-Manager` in your script depending what you would use, currently i removed iwd and going with nm.

**Comment by czrcbl** [comment]
@fisika1729 

I am not even sure if the DHCP was being actually handled by `iwd` after the change.
Anyway, after the change, I was able to reach the web, but I would still get the DHCP issue, requiring the manual reconnect to the wifi network as before.

Thanks, I will test `systemctl restart iwd` later.

Decided to go with a simpler solution, I've linked the router on living room to my desktop on the office with a 10 meters Ethernet cable going through the corridor's floor. 😅

**Comment by fisika1729** [comment]
> @fisika1729 
> 
> I am not even sure if the DHCP was being actually handled by `iwd` after the change.
> Anyway, after the change, I was able to reach the web, but I would still get the DHCP issue, requiring the manual reconnect to the wifi network as before.
> 
> Thanks, I will test `systemctl restart iwd` later.
> 
> Decided to go with a simpler solution, I've linked the router on living room to my desktop on the office with a 10 meters Ethernet cable going through the corridor's floor. 😅


Lmao, simple and effective.

**Comment by ColtonIdle** [comment]
hit this issue again. this time with a brand new framework 12 laptop install. on first boot i was able to connect to wifi. no problems browsing the web, etc. rebooted the laptop. and it said wifi connected, but can't ping anything. chrome says no network connection. and when i click the full wifi bars in the top right corner, no TUI appears.

im on 3.0.2

to be clear. `sudo rfkill unblock all` fixed the issue 😭

**Comment by dhh** [comment]
I've had the same issue on my new Framework 12. I've alerted @eclecticc, and I believe his team is looking into it. It's not related to this issue with the rfkill solution, though.

**Comment by eclecticc** [comment]
For folks seeing this on Framework Laptop 13, could you share which generation (or Wi-Fi module) and which kernel version.  `lspci` and `uname -r`

**Comment by ColtonIdle** [comment]
this did originally happen to me on a framework 13 (but also the 12 as mentioned above since i just received it!)
on the 13 it's only seemed to happen once. then once i ran the rfkill command then it hasn't happened again. likewise on the 12 it hasn't happened again.

not sure if its helpful but here it is

```
lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Krackan IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1124
00:01.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1125
00:01.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1125
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1124
00:02.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1126
00:02.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Device 1126
00:03.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1124
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1124
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Krackan Internal PCIe GPP Bridge 0 to Bus A
00:08.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Krackan Internal PCIe GPP Bridge 0 to Bus B
00:08.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Krackan Internal PCIe GPP Bridge 0 to Bus C
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 71)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Data Fabric; Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Data Fabric; Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Data Fabric; Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Data Fabric; Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Data Fabric; Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Data Fabric; Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Data Fabric; Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Krackan Data Fabric; Function 7
bf:00.0 Non-Volatile memory controller: MAXIO Technology (Hangzhou) Ltd. NVMe SSD Controller MAP1202 (DRAM-less) (rev 01)
c0:00.0 Network controller: Intel Corporation Wi-Fi 6E(802.11ax) AX210/AX1675* 2x2 [Typhoon Peak] (rev 1a)
c1:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Krackan [Radeon 840M / 860M Graphics] (rev c3)
c1:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Radeon High Definition Audio Controller [Rembrandt/Strix]
c1:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Strix/Krackan/Strix Halo CCP/ASP
c1:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Device 1128
c1:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Audio Coprocessor (rev 71)
c1:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h/19h/1ah HD Audio Controller
c2:00.0 Non-Essential Instrumentation [1300]: Advanced Micro Devices, Inc. [AMD] Krackan PCIe Dummy Function
c2:00.1 Signal processing controller: Advanced Micro Devices, Inc. [AMD] Strix/Krackan/Strix Halo Neural Processing Unit (rev 20)
c3:00.0 USB controller: Advanced Micro Devices, Inc. [AMD] Device 1118
c3:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Device 111c
c3:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Device 111e
c3:00.5 USB controller: Advanced Micro Devices, Inc. [AMD] Device 1120
c3:00.6 USB controller: Advanced Micro Devices, Inc. [AMD] Device 1121
```

```
uname -r
6.16.10-arch1-1
```

**Comment by fisika1729** [comment]
@dhh after recent updates network issue appears to no longer troublesome, though my current configuration is iwd+nm, if i disable iwd i still face isseus, but not with both up.

**Comment by ColtonIdle** [comment]
So I installed omarchy 3.1.1 from the iso today on my brand new framework desktop. what was interesting was that on first boot the 3 "tutorial" notifications (keybindings, update, wifi), only 2 of them showed up. i clicked on the wifi icon manually and then tried to sign into my wifi with no luck. after i would enter the password. nothing would happen. wouldn't connect. no error. etc. turning off the wlan0 in impala and turning back on resulted with no changes.

i ended up reinstalling omarchy. same iso. and this time. all 3 tutorial notifications showed up. and i could connect to wifi without issue. lol.

**Comment by ColtonIdle** [comment]
had/wanted to reinstall omarchy again on the framework desktop. got the wifi issue again. this time all 3 tutorial notifications showed up. so i guess thats not related.

`sudo rfkill unblock all` fixed it without having to reinstall the OS for a 4th time. lol

**Comment by AndrijaSkontra** [comment]
Every time I boot my laptop I have to manually click the wifi icon and connect, anyone else with this issue?

**Comment by fisika1729** [comment]
> Every time I boot my laptop I have to manually click the wifi icon and connect, anyone else with this issue?

omarchy version? current one shouldn't have this issue most likely, the issue can some time occurs as the wifi icon shows connected but the icon relays as not connected

**Comment by AndrijaSkontra** [comment]
Should be latest, installed just a few weeks ago, this is my `about`. 

<img width="1858" height="1328" alt="Image" src="https://github.com/user-attachments/assets/d33e1e1c-855f-40b6-a36f-960822ea1d24" />

> the issue can some time occurs as the wifi icon shows connected but the icon relays as not connected

It's not this since browser pages don't load until I connect.

Running omarchy on ThinkPad X1 Carbon Gen 8.

**Comment by issam-hub** [comment]
my solution for now is that i just run `sudo systemctl restart iwd` restarting iwd and it works, still annoying but still a work around

**Comment by dhh** [comment]
Closing because Quattro replaces the iwd, Impala, and systemd-networkd stack with NetworkManager and the native network panel. Please open a new issue if this reproduces on Quattro.
