### ISSUE TITLE
Kernel panic after update

### ISSUE THREAD

**Issue by RodriMora** [basecamp/omarchy#3231]
### System details

AMD Ryzen, Nvidia 4060, Omarchy 3.1.5

### What's wrong?

After a regular Omarchy update today at 2:00pm UTC, rebooting results in a kernel panic. I've seen reports in reddit too:
https://www.reddit.com/r/omarchy/comments/1oqwwd6/kernel_panic_after_fresh_install_and_update/

![Image](https://github.com/user-attachments/assets/71d4ab58-774a-40fa-9e96-2d28797d2637)

**Comment by ljrobins** [comment]
Prior discussion in #3154

I and others are having the same issue! Dell Latitude E7470.

**Comment by whargrove** [comment]
I was able to workaround this by booting from Omarchy directly, instead of booting Limine first. I had changed the boot order so that Limine was first, but since it is now borked I can still boot directly to Omarchy. Confirms it is likely an issue with the limine conf.

**Comment by bashln** [comment]
> I was able to workaround this by booting from Omarchy directly, instead of booting Limine first. I had changed the boot order so that Limine was first, but since it is now borked I can still boot directly to Omarchy. Confirms it is likely an issue with the limine conf.

I can confirm that this actually works.

Had the same kernel panic a few minutes ago and tried this. Everything works great

**Comment by cazador11** [comment]
Got the same issue

**Comment by bashln** [comment]
> Got the same issue

Try what @whargrove mentioned and let us know if it worked or not, please.

**Comment by clouraLabs** [comment]
I can confirm this issue as well. After today's update, I'm experiencing the same kernel panic on boot when using Limine bootloader.

The workaround mentioned by @whargrove works for me - bypassing Limine and booting directly to Omarchy resolves the panic. This strongly suggests the recent update introduced a compatibility issue with the Limine bootloader configuration.

Would it be possible to get more details on what changed in the update that might affect bootloader compatibility? This seems to be affecting multiple users across different hardware configurations.

**Comment by SirenGlitch** [comment]
> Would it be possible to get more details on what changed in the update that might affect bootloader compatibility? This seems to be affecting multiple users across different hardware configurations.

https://github.com/limine-bootloader/limine/commit/e06cc37f685332e8c149b9e6fbccc6d7f61ed5e2 Changes the order Limine looks for configs using

**Comment by jubiloso** [comment]
I guess **.local/share/omarchy/migrations/1761241493.sh** should have used the new path for limine.conf

```
echo "Cleanup extra UKI if needed to prevent errors"
if [[ -f /boot/EFI/linux/omarchy_linux.efi ]] && [[ -f /boot/EFI/linux/$(cat /etc/machine-id)_linux.efi ]]; then
  sudo rm -f /boot/EFI/Linux/$(cat /etc/machine-id)_linux.efi

  if grep -q "/boot/EFI/Linux/$(cat /etc/machine-id)_linux.efi" /boot/limine.conf; then
    echo -e "Resetting limine config\n(you may need to re-add other entries via sudo limine-update)"

    sudo mv /boot/limine.conf /boot/limine.conf.bak
  sudo tee /boot/limine.conf <<EOF >/dev/null                    ###### <------------------------------------------------- HERE ???
### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: Omarchy Bootloader
interface_branding_color: 2
hash_mismatch_panic: no

term_background: 1a1b26
backdrop: 1a1b26

# Terminal colors (Tokyo Night palette)
term_palette: 15161e;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;a9b1d6
term_palette_bright: 414868;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;c0caf5

# Text colors
term_foreground: c0caf5
term_foreground_bright: c0caf5
term_background_bright: 24283b

EOF
    sudo limine-update
    sudo limine-snapper-sync
  fi
fi
```

**Comment by allandt-numan** [comment]
Installed Omarchy for the first time on an old Asus Centrino N58, did the update while I poked around at all the new toys, rebooted, same issue.

Can I ask how to boot into omarchy directly? I've only used grub before (ubuntu user) so I'm not used to the limine bootloader

**Comment by SirenGlitch** [comment]
> Can I ask how to boot into omarchy directly? I've only used grub before (ubuntu user) so I'm not used to the limine bootloader

From [this reddit comment](https://www.reddit.com/r/omarchy/comments/1oqwwd6/comment/nnm5h08/): "Quick fix is to manually edit the boot entry and change the protocol to efi_chainload and the path to /EFI/Linux/omarchy_linux.efi"

Then from there either delete `/boot/EFI/limine/limine.conf` or copy `/boot/limine.conf` into its place (per @jubiloso's [workaround](https://github.com/basecamp/omarchy/issues/3154#issuecomment-3503746701)

**Comment by allandt-numan** [comment]
does the `module_path` also need to be updated (currently it matches path but with the addition of .img on the end)

**Comment by SirenGlitch** [comment]
> does the `module_path` also need to be updated (currently it matches path but with the addition of .img on the end)

Shouldn't do, should just work

**Comment by MrHPotter** [comment]
Thanks. Had the same issue on ryzen 5800x. Copyong the limine config seems to have done the trick

**Comment by C0DE33301** [comment]
I got the same issue, Framework 16

**Comment by C0DE33301** [comment]
> I was able to workaround this by booting from Omarchy directly, instead of booting Limine first. I had changed the boot order so that Limine was first, but since it is now borked I can still boot directly to Omarchy. Confirms it is likely an issue with the limine conf.

This works! Viewing from the Boot Manager. I have two options available, Limine & EFI Hard Drive. Like you mentioned not selecting Limine but the main drive for omarchy, for me it's EFI Hard Drive. It boots normally. Thank you!

Computer: Framework 16

**Comment by hazagrande** [comment]
> I was able to workaround this by booting from Omarchy directly, instead of booting Limine first. I had changed the boot order so that Limine was first, but since it is now borked I can still boot directly to Omarchy. Confirms it is likely an issue with the limine conf.

This worked for me too. Thanks!

**Comment by Winterbones01** [comment]
My first install of omarchy. My first update borks it. Too funny. Thanks for the way out.

**Comment by yburakyo** [comment]
i can’t seem to bypass limine, when i enter my boot options menu i only see:

M.2: Limine
USB:

HP Elitebook 840 G5 with i7 8550U

i also tried the ”manually edit the boot entry and change the protocol to efi_chainload and the path to /EFI/Linux/omarchy_linux.efi"” method but i get an error on that…

Really fast edit: Got in!

in the boot options there was a **boot from file** option, which prompted me to manually go down the file tree to finally choose 

/EFI/Linux/omarchy_linux.efi

**Comment by SirenGlitch** [comment]
> My first install of omarchy. My first update borks it. Too funny. Thanks for the way out.

@Winterbones01 I do wish to point out that it doesn't seem to be an Omarchy problem to me. Limine received a commit 4 days ago (see above in the thread) that changed the order the config was loaded in. This caused a (presumably default) config file next to the binary to be loaded, rather than the intended Omarchy one that would load the system properly.

Obviously I respect your decision to go elsewhere, but should you reconsider, there are plenty of workarounds in this thread and #3154 that you can try, or use a Limine version before v10

**Comment by RodriMora** [comment]
After being able to boot using the Omarchy bootloader instead of the Limine. In order to revert the Limine version:

Last working Limine version is `9.6.7-1`
Download and install it:
`sudo pacman -U https://archive.archlinux.org/packages/l/limine/limine-9.6.7-1-x86_64.pkg.tar.zst`

Check the version:
`pacman -Qi limine | sed -n 's/^Version *: //p'`

Freeze the version:
`sudoedit /etc/pacman.conf`
Under [options], add or edit the line:
`IgnorePkg = limine`

imine-mkinitcpio-hook or limine-snapper-sync may need to be frozen too (not sure):
`IgnorePkg = limine limine-mkinitcpio-hook limine-snapper-sync`

**Comment by dhh** [comment]
This has been fixed in 3.1.6. @ryanrhughes is working on an easy step-by-step to get anyone who managed to catch this bad update back in business.

**Comment by RodriMora** [comment]
> This has been fixed in 3.1.6. [@ryanrhughes](https://github.com/ryanrhughes) is working on an easy step-by-step to get anyone who managed to catch this bad update back in business.

Confirming this works, no need to freeze the Limine package any more https://github.com/basecamp/omarchy/issues/3231#issuecomment-3505070605

Closing this as ryan will probably post the guide somewhere else.

**Comment by ryanrhughes** [comment]
Guide is here https://github.com/basecamp/omarchy/discussions/3236

**Comment by graetz23** [comment]
> > Can I ask how to boot into omarchy directly? I've only used grub before (ubuntu user) so I'm not used to the limine bootloader
> 
> From [this reddit comment](https://www.reddit.com/r/omarchy/comments/1oqwwd6/comment/nnm5h08/): "Quick fix is to manually edit the boot entry and change the protocol to efi_chainload and the path to /EFI/Linux/omarchy_linux.efi"
> 
> Then from there either delete `/boot/EFI/limine/limine.conf` or copy `/boot/limine.conf` into its place (per [@jubiloso](https://github.com/jubiloso)'s [workaround](https://github.com/basecamp/omarchy/issues/3154#issuecomment-3503746701)

Did copy it and made updated via limine-install in /boot .. then the limine boot menu looked fine and worked well; no need to change anything in conf here, just copy.

**Comment by abiiranathan** [comment]
It's tough. I caught this bug and suggested fixes still unable to work for me. Losing my work 😭
