### ISSUE TITLE
Videos not playing after recent update (Omarchy v3.2.3)

### ISSUE THREAD

**Issue by Rezy-Dev** [basecamp/omarchy#3891]
### System details

Nvidia RTX 3050ti | Omarchy v3.2.3

### What's wrong?

After updating the system to Omarchy v3.2.3, video playback is broken on Chromium-based browsers (Brave, Chromium, Chrome).

# Observed behavior
1. Videos do not play or show a black screen
2. Severe lag, flickering, and jittering
3. Browser may crash in some cases

# Root Cause
Chromium defaults to ANGLE (egl-angle) on Wayland.
With the Omarchy v3.2.3 update (Mesa + Wayland stack), the ANGLE → EGLImage → DMA-BUF video rendering path is broken, causing decoded video frames to fail to present.

# Workaround / Fix
Force Chromium to use desktop OpenGL instead of ANGLE by adding the following flag at your browser's config (`~/.config/brave-flags.conf` for brave and `~/.config/chromium-flags.conf` for chromium):
```bash
--use-gl=desktop
``` 

After restarting the browser, video playback works normally.

**Comment by EERomeo** [comment]
I have this problem with the Brave browser as well.
I used 
`--ozone-platform=x11`
in my brvae-flags.conf to make it work for now.

**Comment by Tsurgcom** [comment]
Haha, I also was just thinking of opening an issue.
Here is my hardware:

<img width="597" height="708" alt="Image" src="https://github.com/user-attachments/assets/3405362f-82e3-4382-820b-c87c084fa505" />

I will see if `--use-gl=desktop` fixes it for me.
Edit: It does.
It is strange that I do not have this bug on my other (older) pc which got omarchy installed first.

**Comment by MirasMustimov** [comment]
adding `--use-gl=desktop` fixes videos not playing for me but disables hardware acceleration

<img width="671" height="440" alt="Image" src="https://github.com/user-attachments/assets/f3f18a08-2518-40ec-8682-5ccbc81b682a" />


my `brave-flags.conf` is 
--ozone-platform=wayland
--ozone-platform-hint=wayland
--enable-features=TouchpadOverscrollHistoryNavigation
--load-extension=~/.local/share/omarchy/default/chromium/extensions/copy-url
--use-gl=desktop
 

<img width="443" height="345" alt="Image" src="https://github.com/user-attachments/assets/a61ed143-b2ad-4bc9-ba04-21f86af158cf" />

**Comment by EERomeo** [comment]
Well Miras, after seeing your post I checked mine and I have the same report. But... I have YT opened in another window and I also have gpu monitor in my waybar, if I pause the video on YT my GPU use goes to 0, if I the video is playing the GPU use is ~30%. So it is somehow using the GPU?

**Comment by burakakca** [comment]
<img width="852" height="583" alt="Image" src="https://github.com/user-attachments/assets/50f6d875-ce4b-4c03-b05a-15f2eee7270c" />

https://github.com/user-attachments/assets/c2139300-fefe-4f34-8702-ca7412910950

**Comment by atiladefreitas** [comment]
yo @burakakca which browser is that? I'm facing the exact same issue in Helium Browser

I honestly think that is something related to Chromium itself, because this issue occurs only in Chromium based browsers, like Google Chrome, Brave, Helium and in Firefox based ones like Zen Browse this problem does not happens. Still investigating

**Comment by burakakca** [comment]
@atiladefreitas chromium but i tried brave same thing. The weird things is it does not occur in every video but most of them like that

**Comment by dhh** [comment]
@hjanuschka Does this ring any bells for you?

**Comment by MirasMustimov** [comment]
here is error log 

~ ❯ brave
[55623:55623:1216/205142.932547:ERROR:chrome/browser/ui/views/user_education/impl/browser_user_education_interface_impl.cc:154] Attempting to show IPH IPH_DiscardRing before browser initialization complete; IPH will not be shown.
[55623:55623:1216/205142.968996:ERROR:ui/ozone/platform/wayland/host/wayland_wp_image_description.cc:219] Incomplete image description info from compositor.
[55623:55623:1216/205143.537672:ERROR:ui/ozone/platform/wayland/host/wayland_wp_image_description.cc:219] Incomplete image description info from compositor.
[55676:55676:1216/205155.814871:ERROR:ui/gl/angle_platform_impl.cc:42] ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
ERR: ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
[55676:55676:1216/205155.814953:ERROR:ui/gl/scoped_egl_image.cc:23] Failed to create EGLImage: EGL_SUCCESS
[55676:55676:1216/205155.815001:ERROR:ui/ozone/common/native_pixmap_egl_binding.cc:76] Unable to initialize binding from pixmap
[55676:55676:1216/205155.815067:ERROR:gpu/command_buffer/service/shared_image/ozone_image_backing.cc:316] OzoneImageBacking::ProduceSkiaGanesh failed to create GL representation
[55676:55676:1216/205155.815111:ERROR:gpu/command_buffer/service/shared_image/shared_image_manager.cc:404] SharedImageManager::ProduceSkia: Trying to produce a Skia representation from an incompatible backing: OzoneImageBacking
[55676:55676:1216/205155.823580:ERROR:ui/gl/angle_platform_impl.cc:42] ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
ERR: ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
[55676:55676:1216/205155.823698:ERROR:ui/gl/scoped_egl_image.cc:23] Failed to create EGLImage: EGL_SUCCESS
[55676:55676:1216/205155.823784:ERROR:ui/ozone/common/native_pixmap_egl_binding.cc:76] Unable to initialize binding from pixmap
[55676:55676:1216/205155.823847:ERROR:gpu/command_buffer/service/shared_image/ozone_image_backing.cc:316] OzoneImageBacking::ProduceSkiaGanesh failed to create GL representation
[55676:55676:1216/205155.823897:ERROR:gpu/command_buffer/service/shared_image/shared_image_manager.cc:404] SharedImageManager::ProduceSkia: Trying to produce a Skia representation from an incompatible backing: OzoneImageBacking
[55676:55676:1216/205155.828306:ERROR:ui/gl/angle_platform_impl.cc:42] ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009

the last error keeps repeating while video flickers and lags


nvidia info
~ ❯ nvidia-smi
Tue Dec 16 20:57:36 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8             11W /   80W |     252MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1761      G   /usr/lib/Xorg                             4MiB |
|    0   N/A  N/A            2169      G   Hyprland                                  2MiB |
|    0   N/A  N/A            2245    C+G   /usr/bin/swayosd-server                   7MiB |
|    0   N/A  N/A            2317    C+G   /usr/bin/walker                          46MiB |
|    0   N/A  N/A           51323    C+G   /usr/lib/zed/zed-editor                 122MiB |
+-----------------------------------------------------------------------------------------+



brave flags
~ ❯ cat ~/.config/brave-flags.conf
```
--ozone-platform=wayland
--ozone-platform-hint=wayland
--enable-features=TouchpadOverscrollHistoryNavigation
--load-extension=~/.local/share/omarchy/default/chromium/extensions/copy-url
```

**Comment by redredkrovy** [comment]
> adding `--use-gl=desktop` fixes videos not playing for me but disables hardware acceleration
> 
> <img alt="Image" width="671" height="440" src="https://private-user-images.githubusercontent.com/25564131/526962142-f3f18a08-2518-40ec-8682-5ccbc81b682a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5MDkyODgsIm5iZiI6MTc2NTkwODk4OCwicGF0aCI6Ii8yNTU2NDEzMS81MjY5NjIxNDItZjNmMThhMDgtMjUxOC00MGVjLTg2ODItNWNjYmM4MWI2ODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjE2VDE4MTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDJiMzM5NDZjMDFjM2JhMGIwYmM4MzAxMWYwMWNlMTg4YTg5M2M3ODcyZDM4ZjNkZTI0ZTQxNjBlMzc0MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MRGAQE6gq7JSSMo9273BXLBNZs4bePdvT-CprO0_HeY">
> my `brave-flags.conf` is --ozone-platform=wayland --ozone-platform-hint=wayland --enable-features=TouchpadOverscrollHistoryNavigation --load-extension=~/.local/share/omarchy/default/chromium/extensions/copy-url --use-gl=desktop
> 
Having the same issue.  Flag is set, hardware acceleration is turned on but it's definitely still using software rendering.

**Comment by hjanuschka** [comment]
@dhh seems to be related to some angel on wayland problem, going to investigate

**Comment by hjanuschka** [comment]
might be same as: https://github.com/basecamp/omarchy/issues/3899

**Comment by hjanuschka** [comment]
any one up for a alpha test, i dont have this kind of hardware available but i think i found a fix

**Comment by EERomeo** [comment]
sure for a test, what do you need?

**Comment by sntsntsntsnt** [comment]
> any one up for a alpha test, i dont have this kind of hardware available but i think i found a fix

i have this issue as well

this is my device

<img width="1050" height="720" alt="Image" src="https://github.com/user-attachments/assets/c83884d8-af00-44c3-9f1f-b3d67ec9d632" />

**Comment by atiladefreitas** [comment]
I can test @hjanuschka

**Comment by hjanuschka** [comment]
https://github.com/omacom-io/omarchy-chromium/releases/tag/v143.0.7499.109-wip-ozone would be nice if one of you could install run and verify it.

it's basically omarchy-chromium with this patch applied: https://chromium-review.googlesource.com/c/chromium/src/+/7265225


if it works, i'll proceed getting it into chromium and its forks!

**Comment by hjanuschka** [comment]
cc @atiladefreitas @sntsntsntsnt 

> i hope you know how to revert go back to stable, just in case something goes south

**Comment by atiladefreitas** [comment]
@hjanuschka I still with some problems. Videos are ok but some websites still breaking, especially the ones that has animation

https://github.com/user-attachments/assets/7da68daf-0e70-492c-b465-7873178fc8b3

**Comment by EERomeo** [comment]
I just tested it, it's the same for me! At least on reddit.com as soon as a video enters the viewport!

**Comment by hjanuschka** [comment]
@atiladefreitas  just for a cross check, it improved? or is it exactly the same as before?

**Comment by sntsntsntsnt** [comment]
Testing it. Youtube seems to work. I'm still having issues with video playing elsewhere. The mp4 that is in one of the messages above this one breaks my page. I will let you know if anything else improves.

Edit: Youtube player started breaking again (previews work just fine).

**Comment by atiladefreitas** [comment]
@hjanuschka videos are now ok, but the website animations still breaking as before.

**Comment by hjanuschka** [comment]
working on it, in the meantime

could you try launching it with:

```
chromium  --enable-hardware-overlays=""
```

to help my verify my idea

**Comment by burakakca** [comment]
https://github.com/user-attachments/assets/24d09d4d-3295-4f6e-a8cd-ed4bbd7444e9


> chromium  --enable-hardware-overlays=""

i test it this after video but same

**Comment by hjanuschka** [comment]
make sure, before installing or after, to kill all chromium's 

```
killall -9 chromium
```

and then launch, if a single instance is running, even after installation it is not working.

**Comment by atiladefreitas** [comment]
@hjanuschka The websites that was breaking now it's working, I've did nothing more from the latest video I've sent (just had to reboot my laptop), I think that a old process was running. Look:

https://github.com/user-attachments/assets/84a2d39a-59ae-4ae1-bea7-47b405ba1411

here is the logs form `--enable-hardware-overlays=""`

```bash
❯ chromium  --enable-hardware-overlays=""
[17402:17402:1216/175655.191942:ERROR:media/gpu/vaapi/vaapi_wrapper.cc:1628] vaInitialize failed: unknown libva error
[17362:17362:1216/175659.279100:ERROR:mojo/public/cpp/bindings/lib/interface_endpoint_client.cc:732] Message 1 rejected by interface blink.mojom.WidgetHost
[17362:17382:1216/175659.316625:ERROR:google_apis/gcm/engine/registration_request.cc:292] Registration response error message: DEPRECATED_ENDPOINT
[17362:17382:1216/175720.293978:ERROR:google_apis/gcm/engine/registration_request.cc:292] Registration response error message: DEPRECATED_ENDPOINT
[17362:17362:1216/175729.958528:ERROR:mojo/public/cpp/bindings/lib/interface_endpoint_client.cc:732] Message 1 rejected by interface blink.mojom.WidgetHost
[17362:17382:1216/175824.379305:ERROR:google_apis/gcm/engine/registration_request.cc:292] Registration response error message: DEPRECATED_ENDPOINT
```

**Comment by burakakca** [comment]
> make sure, before installing or after, to kill all chromium's

i did but for me still i'm having same problem

**Comment by hjanuschka** [comment]
@atiladefreitas that is good, we are on to something!
and if you killall -9 chromium and launch again without `--enable-hardware-overlays=""`  videos work, but website-scroll is flickering?

**Comment by hjanuschka** [comment]
@burakakca that might be a total different issue?! can you paste your logs?

**Comment by atiladefreitas** [comment]
@hjanuschka without the flag, websites flickered again

https://github.com/user-attachments/assets/3a102348-366a-408f-acd8-0662d70857b2

**Comment by hjanuschka** [comment]
alright that is great! so in worst-case we have a workaround.
can you try stable chromium with flag - lets see if that would work too.

currrently building another WIP to see if we can fix flicker without flag

**Comment by atiladefreitas** [comment]
@hjanuschka the flag solves everything... I also tried the flag in other chromium-based browsers like Helium and Brave that was with the same problem and was solved with the flag

edit: even google chrome was with this problem

**Comment by burakakca** [comment]
```bash
~ ❯ chromium  --enable-hardware-overlays=""
[2223:2243:1217/001417.253628:ERROR:google_apis/gcm/engine/registration_request.cc:292] Registration response error message: DEPRECATED_ENDPOINT
[2265:2265:1217/001420.817620:ERROR:ui/gl/angle_platform_impl.cc:42] ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
ERR: ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
[2265:2265:1217/001420.817778:ERROR:ui/gl/scoped_egl_image.cc:23] Failed to create EGLImage: EGL_SUCCESS
[2265:2265:1217/001420.817897:ERROR:ui/ozone/common/native_pixmap_egl_binding.cc:76] Unable to initialize binding from pixmap
[2265:2265:1217/001420.818067:ERROR:gpu/command_buffer/service/shared_image/ozone_image_backing.cc:316] OzoneImageBacking::ProduceSkiaGanesh failed to create GL representation
[2265:2265:1217/001420.818204:ERROR:gpu/command_buffer/service/shared_image/shared_image_manager.cc:404] SharedImageManager::ProduceSkia: Trying to produce a Skia representation from an incompatible backing: OzoneImageBacking
```

**Comment by hjanuschka** [comment]
@atiladefreitas  that is great news!! and confirms my theory.

could you try https://github.com/omacom-io/omarchy-chromium/releases/tag/v143.0.7499.109-wip-ozone2 without any flag?
this should root cause fix it (hopefully 🤞 )


killall, install, no flag, normal launch

**Comment by atiladefreitas** [comment]
thanks god we have at least a workaroud, I hate inspect element in firefox-based browsers 🙏🏻

**Comment by EERomeo** [comment]
for me it's not working, eve with the flag! I get a bunch of these errors on the terminal:

ERR: ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
[2092272:2092272:1216/232040.291200:ERROR:ui/gl/scoped_egl_image.cc:23] Failed to create EGLImage: EGL_SUCCESS
[2092272:2092272:1216/232040.291244:ERROR:ui/ozone/common/native_pixmap_egl_binding.cc:76] Unable to initialize binding from pixmap
[2092272:2092272:1216/232040.291309:ERROR:gpu/command_buffer/service/shared_image/ozone_image_backing.cc:316] OzoneImageBacking::ProduceSkiaGanesh failed to create GL representation
[2092272:2092272:1216/232040.291350:ERROR:gpu/command_buffer/service/shared_image/shared_image_manager.cc:404] SharedImageManager::ProduceSkia: Trying to produce a Skia representation from an incompatible backing: OzoneImageBacking

**Comment by hjanuschka** [comment]
@EERomeo @burakakca  your logs both fail due to driver issues and the last WIP release should fix it, just make sure you atleast once killall -9 chromium - just make sure no old instance is alive

**Comment by atiladefreitas** [comment]
all good @hjanuschka

**Comment by hjanuschka** [comment]
> all good [@hjanuschka](https://github.com/hjanuschka)

last WIP release without flags - all issues fixed?

**Comment by EERomeo** [comment]
ok, what driver issues? 
Last wip, for me it's the same, flags or no flags.
With:
~ ❯ killall -9 chromium
chromium: no process found

**Comment by atiladefreitas** [comment]
@hjanuschka sorry did not tested the last WIP, still flicking

**Comment by burakakca** [comment]
> @atiladefreitas  that is great news!! and confirms my theory.
> 
> could you try https://github.com/omacom-io/omarchy-chromium/releases/tag/v143.0.7499.109-wip-ozone2 without any flag?
> this should root cause fix it (hopefully 🤞 )
> 
> 
> killall, install, no flag, normal launch
> 

i tried this also but nothing changed. i restart my laptop and i make sure there is no running instance

**Comment by EERomeo** [comment]
you know what else works, it's the way I was using Brave before the issue posted here... I put
--ozone-platform=x11 in the brave-flags.conf
This works and it gives this report:

<img width="597" height="466" alt="Image" src="https://github.com/user-attachments/assets/527c4b9d-1ab3-4ca6-93db-52863bfbbdd4" />

**Comment by hjanuschka** [comment]
ok another WIP ozone3: https://github.com/omacom-io/omarchy-chromium/releases/tag/v143.0.7499.109-wip-ozone3
@atiladefreitas lets hope 👍  this tries addressing it from a deeper angle.

**Comment by atiladefreitas** [comment]
still :\

**Comment by hjanuschka** [comment]
gdm, ok running out of ideas, its near impossible to trial and error this without having hardware to reproduce

**Comment by atiladefreitas** [comment]
there is any log that I can send? @hjanuschka

**Comment by EERomeo** [comment]
same here, flags/no flags

**Comment by atiladefreitas** [comment]
at least I can set the system to lauch the browser with the flag as default :)

**Comment by hjanuschka** [comment]
ok filed a bug on chromium, lets hope someone from the right team will pick it up:

https://issues.chromium.org/issues/469458278

**Comment by pyrozhok** [comment]
The same bug appears only in Chromium-based browsers starting with version 143. I downgraded Chromium to version 142, and it works fine.

**Comment by hjanuschka** [comment]
while waiting on a bug response, could you try installing latest omarchy-chromium and/or the google-chrome-canary?
if any of them works we could potentially more easily find a solution

**Comment by MrF0o** [comment]
Same here GIFs and videos glitching and doesn't play.

**Comment by pyrozhok** [comment]
> while waiting on a bug response, could you try installing latest omarchy-chromium and/or the google-chrome-canary? if any of them works we could potentially more easily find a solution

Tried google chrome canary 145.0.7582.1 - bug exists

https://github.com/user-attachments/assets/b9820e20-2d0c-4a6e-bafb-581efda6f7e2

**Comment by stephanedemotte** [comment]
Chromium waylang bug spotted https://issues.chromium.org/issues/469458278

**Comment by redredkrovy** [comment]
> Chromium waylang bug spotted https://issues.chromium.org/issues/469458278

Yes, that's the bug report @hjanuschka submitted and linked earlier in this thread.

**Comment by Duke-fleed** [comment]
No news about this? Been weeks already:/

**Comment by dhh** [comment]
It appears that this is fixed with nvidia 590 drivers and chrome 143. But before we can sync the 590 drivers to the stable channel, we need to deal with the fallback for older nvidia cards. But for folks with modern cards, you can hop on the edge channel to see if that solves it for you: _Update > Channel > Edge_.

**Comment by ryanrhughes** [comment]
Finally back home and able to do some testing on my Nvidia machine. I'm not able to recreated this error using an RTX 5090 with the drivers `nvidia-open-dkms 590.48.01-1` in either `omarchy-chromium 143.0.7499.146-16` or `brave-bin 1:1.85.118-1`. Both play just fine.

This appears to be an Nvidia driver issue to me.

**Comment by IshpreetSingh8264** [comment]
I am right now on `Brave: 1.85.118 Chromium: 143.0.7499.169 (Official Build) (64-bit)`. I updated omarchy in the "Edge" channel as mentioned and my current nvidia 4070's drivers are: `NVIDIA-SMI 590.48.01 Driver Version: 590.48.01`

I turned on hardware acceleration in brave, and the stuttering issue is still there. stuttering, videos not playing, the whole browser hangs etc.
Youtube videos wont even play (audio works), instagram reels or twitter videos just hang the whole browser unless i switch the tab.

**Comment by PraiseTheDuck** [comment]
I did a clean install and watched some YouTube videos with no issue at all. But after some time it came back with no apparent reason. Now I switched to the Edge Channel, but it didn't help.

**Comment by IshpreetSingh8264** [comment]
Well, the issue started like that for me as well. When i updated omarchy, I didnt exactly went through the problem right after. It came after some time when I was scrolling through instagram.

**Comment by ryanrhughes** [comment]
Be sure to reboot after update to ensure you're loaded up on the new drivers as well. I'll keep running videos and see if I can't get mine to start stuttering but so far it's been solid.

**Comment by i-doll** [comment]
I switched to edge channel, and I still experience issues in both Chrome 143 and Helium 0.7.7 based on chromium 143 with RTX 4070 max-q with the 590 drivers, interestingly enough, videos sometimes work fine, but other times they just play the audio:
https://github.com/user-attachments/assets/62f800d0-d1db-4bfb-bc62-2e5258bb6d28

**Comment by woochaq** [comment]
I've updated channel Edge and on Brave and Chromium I still got the same problem

NVIDIA RTX 500 Ada Generation Laptop GPU
Brave: 1.85.118
Chromium: 143.0.7499.169
```
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  590.48.01  Release Build  (root@)
GCC version:  gcc version 15.2.1 20251112 (GCC)
```

**Comment by dhh** [comment]
Would be good with some triangulation. For people having problems, can you replicate those issues on another Linux distro running the same versions? Could someone try downgrading to Chrome 142 and see if that fixes things? Or try downgrading the Nvidia drivers?

**Comment by IshpreetSingh8264** [comment]
I downgraded my nvidia drivers the day i got the issue for the first time and that didnt help

**Comment by EERomeo** [comment]
My question would be... what is different between my system (working now) and systems that still have the problem. On my end Brave/Chromium/Omarchy Chromium now work.

**Comment by IshpreetSingh8264** [comment]
This below is what is happening for me:-
I have graphics acceleration turned on btw.

https://github.com/user-attachments/assets/fcef3c09-5b2f-4fcf-8eed-748b321baeac

**Comment by EERomeo** [comment]
That's the bug I had after the 323 update, here's what works for me now:

<img width="690" height="417" alt="Image" src="https://github.com/user-attachments/assets/546946f9-1983-4b6a-88d0-5c142bfde080" />

<img width="833" height="445" alt="Image" src="https://github.com/user-attachments/assets/72ec2e59-f4d9-48ce-8fed-556b558998ea" />

This combination works without a problem, at least for me.

**Comment by pyrozhok** [comment]
@dhh I did downgrade to 142 (NVIDIA 580.105.08) - works completely fine (with new profile, old prevent loading due conflicts)

**Comment by div-25** [comment]
I reported this issue in the Discord ([post](https://discord.com/channels/1390012484194275541/1454511027415810118) initially. I think I'll add my hardware profile and observed behavior here as well.

Youtube UI wouldn't load upon opening a video (the audio ran just fine). My system also hung often times. I noticed the trail of cursors as shown in the image below. Issue seen on both Chromium and google-chrome-stable.

I disabled hardware acceleration as a workaround in the Chrome settings.

<img width="1003" height="1783" alt="Image" src="https://github.com/user-attachments/assets/c4d82837-00f7-44ed-8e78-7e6e96c21fca" /> 

<img width="1663" height="831" alt="Image" src="https://github.com/user-attachments/assets/bfc7db49-a3cf-4643-a037-7e2529f18851" />

**Comment by atiladefreitas** [comment]
> I did downgrade to 142 (NVIDIA 580.105.08) - works completely fine (with new profile, old prevent loading due conflicts)

@pyrozhok you had to downgrade the linux kernel version or something more?

**Comment by Jamesking56** [comment]
Duplicate of #2800 ?

**Comment by pyrozhok** [comment]
> > I did downgrade to 142 (NVIDIA 580.105.08) - works completely fine (with new profile, old prevent loading due conflicts)
> 
> [@pyrozhok](https://github.com/pyrozhok) you had to downgrade the linux kernel version or something more?

Nope, only browser with new profile

**Comment by BoredVoidAter** [comment]
deleting the GPUCache folder in the chromium profile folder seems to make it work for some time

**Comment by hjanuschka** [comment]
so many variations! :( 

```
--use-gl=desktop
```


should be the most stable solution?! 
if that is true the issue must be in the ANGEL backend, which might be related to recent changes inside chromium, i truly would love to root-cause fix this, but suffer the fact that i cannot reproduce it locally, which makes it almost impossible to iterate and trial and error it.

would love todo two things:

 1) poll - of workarounds that worked, to figure out directions (and potential, "while we search for fix" scenarios)
 2) somone helps me getting access to a system that has the issues in a reproducable state (amazon shopping list; of an affordable system) - then i could deep dive into it.

**Comment by hjanuschka** [comment]
> deleting the GPUCache folder in the chromium profile folder seems to make it work for some time

this is a  interesting path, would like to hear if removing the folder fixes other's issues too

**Comment by EERomeo** [comment]
For me both --use-gl=desktop and --ozone-platform=x11 worked when the bug was present.
Updating Brave and uninstalling Nvidia then installing nvidia-open-dkms fixed it for me. Installed Chromium and Omarchy-chromium with the menu installer after that and all work without a glitch.

**Comment by IshpreetSingh8264** [comment]
Just wanna let you know, @hjanuschka I did ran the script, the issue still persists after cache removal (atleast for me)
it was not fixed even for "some" time

**Comment by Dillpickleschmidt** [comment]
Both --use-gl=desktop and --ozone-platform=x11 didn't work for me, however **I managed to find a workaround that works for hybrid laptops**.
I'm running a Lenovo Legion 7 Pro in hybrid mode (amd iGPU + nvidia dGPU). My dGPU was not going to sleep draining battery so I came across issue #1776.
I went into `~/.config/hypr/hyprland.conf` and commented out these 3 lines so that video processing would use my amd iGPU instead of nvidia:
```
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
```
As a side effect of improving battery, the video issues in chromium are fixed (presumably because I'm not using the nvidia graphics card for rendering them).

It's a band-aid fix that doesn't solve the root issue, but it gives you something usable that doesn't really affect user experience (like disabling hardware rendering entirely).

**Comment by BoredVoidAter** [comment]
--disable-accelerated-video-decode should work universally, skips nvidia like @Dillpickleschmidt solution but just for chromium videos

**Comment by hicles** [comment]
> It appears that this is fixed with nvidia 590 drivers and chrome 143. But before we can sync the 590 drivers to the stable channel, we need to deal with the fallback for older nvidia cards. But for folks with modern cards, you can hop on the edge channel to see if that solves it for you: _Update > Channel > Edge_.

I'm on a modern GPU (5070 MAX) and this did not fix it for me. Seems like this solution might only be for 5090 cards specifically. FYI: I do not recommend anyone to even try this, it breaks all of the default configs because the Omarchy edge update only partially migrated the configs - windows.conf uses the new syntax but all the app-specific configs still use the old syntax which breaks everything.

**Comment by vikkio88** [comment]
this `--use-gl=desktop` worked for me on my dell xps 15 with this video card
```
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
```

Do you know if just changing the default BROWSER to `brave --use-gl=desktop` will make it be effectively the default switch when you launch urls?

**Comment by hjanuschka** [comment]
there is alot of noise, and various "works", "does not work".

please help us to cluster this, and answer with what worked for you in this poll: https://github.com/basecamp/omarchy/discussions/4055

**Comment by comShadowHarvy** [comment]
add --ozone-platform=x11   
nvim ~/.config/chrome-flags.conf
If you are using the AUR package google-chrome, try ~/.config/google-chrome-flags.conf if the above doesn't work. For chromium, it is chromium-flags.conf

it has worked for me. i would prefer it to use wayland but it looks like it was forcing the wrong gpu.
using AI to help me go thew logs i am not expirianced reading gave me 
```

The about-gpu log you uploaded confirms exactly why you are having issues and why switching to X11 is the right move.

Here is what the log tells us about your current (broken) state:

You are definitely on Wayland: The log shows the command line argument --ozone-platform=wayland and the Ozone platform is listed as wayland.

Severe Graphics Errors: The log is flooded with eglCreateImage failed and OzoneImageBacking::ProduceSkiaGanesh failed errors. This basically means Chrome is trying to draw the window contents using Wayland's buffer protocol and failing repeatedly, likely causing flickering, black windows, or crashes.

Hybrid Graphics Conflict:

You are forcing the GPU with --render-node-override=/dev/dri/renderD129 (likely trying to use your NVIDIA card).

However, Chrome reports the Active GPU is GPU1 (Intel).

This mismatch combined with Wayland is a common cause of the eglCreateImage failure.
```

**Comment by lynndylanhurley** [comment]
Reporting what worked for me:

 System Details
  - GPU: Intel Arc Graphics (iGPU) + NVIDIA GeForce RTX 4070 Max-Q (dGPU) - hybrid laptop
  - NVIDIA Driver: nvidia-open-dkms 590.48.01
  - Omarchy channel: Edge

What worked:

`--enable-hardware-overlays=""` in my browser flags config resolved the video playback issues (flickering, black screens, jittering) while keeping hardware acceleration enabled.

`--use-gl=desktop` did not work for me. videos broke pages on youtube, etc (but audio worked fine)

Flags config (brave-flags.conf / chromium-flags.conf / google-chrome-flags.conf):
```
  --ozone-platform=wayland
  --ozone-platform-hint=wayland
  --enable-features=TouchpadOverscrollHistoryNavigation
  --load-extension=~/.local/share/omarchy/default/chromium/extensions/copy-url
  --disable-features=WaylandWpColorManagerV1
  --enable-hardware-overlays=""
```

This seems consistent with the theory that the issue is in the ANGLE hardware overlay path on NVIDIA + Wayland.

**Comment by sepehr500** [comment]
Hardware: NVIDIA RTX 3000 Ada Generation Laptop GPU, driver 590.48.01, Omarchy 3.3.3                            
                                                                                                                  
  Error in logs:  
  ERROR:ui/gl/angle_platform_impl.cc] ImageEGL.cpp: eglCreateImage failed with 0x00003009
  ERROR:ui/gl/scoped_egl_image.cc] Failed to create EGLImage: EGL_SUCCESS
  ERROR:ui/ozone/common/native_pixmap_egl_binding.cc] Unable to initialize binding from pixmap
  ERROR:gpu/command_buffer/service/shared_image/ozone_image_backing.cc] OzoneImageBacking::ProduceSkiaGanesh
  failed to create GL representation
  ERROR:gpu/command_buffer/service/shared_image/shared_image_manager.cc] SharedImageManager::ProduceSkia: Trying
  to produce a Skia representation from an incompatible backing: OzoneImageBacking
  (repeats continuously during video playback)

  What worked: --disable-accelerated-video-decode

  This keeps hardware acceleration enabled for everything except video decode, so no noticeable lag unlike
  --use-gl=desktop.

**Comment by ealexeev** [comment]
FYI, for me, a similar issues cropped up in March 2026, the fix was to disable the "Use vulkan as the graphics backend. – Linux, Android" under chrome://flags

**Comment by raybarrera** [comment]
Variations of this issue have been occurring on and off for me over several versions. The latest two versions have brought it back. (For me, it's brave).

It's a bit of whack-a-mole because sometimes reports focus on hybrid setups with igpus, but am experience similar symptoms over time on a dedicated NVIDIA GeForce RTX 3080, AMD Ryzen 9 5900X (no igpu)

I get green flickers that get worse over time, then eventually a hard-freeze and I need to reset the whole machine.

brave://gpu shows some errors that seem relevant, and related to vaapi:
[2446:2446:0415/111439.023591:WARNING:media/gpu/vaapi/vaapi_wrapper.cc:122] : Should skip nVidia device named: nvidia-drm
[2446:2446:0415/111439.023675:WARNING:media/gpu/vaapi/vaapi_wrapper.cc:1558] : Forcibly using value of --render-node-override
[2446:2446:0415/111439.469411:ERROR:ui/ozone/platform/wayland/gpu/wayland_surface_factory.cc:252] : '--ozone-platform=wayland' is not compatible with Vulkan. Consider switching to '--ozone-platform=x11' or disabling Vulkan
[2446:2446:0415/111439.556253:WARNING:sandbox/policy/linux/sandbox_linux.cc:405] : InitializeSandbox() called with multiple threads in process gpu-process.
[2446:6700:0415/111509.705924:ERROR:media/gpu/vaapi/vaapi_video_decoder.cc:1219] : failed Initialize()ing the frame pool
[2446:6698:0415/111509.725020:ERROR:media/gpu/vaapi/vaapi_video_decoder.cc:1219] : failed Initialize()ing the frame pool
[2446:6726:0415/111510.382731:ERROR:media/gpu/vaapi/vaapi_video_decoder.cc:1219] : failed Initialize()ing the frame pool
[2446:2446:0415/112042.376067:ERROR:ui/gl/egl_util.cc:92] : EGL Driver message (Error) eglCreateContext: Requested version is not supported
[2446:2507:0415/112107.929919:ERROR:components/viz/service/display/display.cc:286] : Frame latency is negative: -0.099 ms

and journalctl -b -1 -k | tail -n 100 > relevant logs:
Apr 15 11:12:41 spear kernel: NVRM: nvAssertOkFailedNoLog: Assertion failed: Out of memory [NV_ERR_NO_MEMORY] (0x00000051) returned from pReuseMappingDb->pMapCb(pReuseMappingDb->pGlobalCtx, pAllocCtx, range, cachingFlags, &token, _reusemappingdbAddMappingCallback) @ mapping_reuse.c:273
Apr 15 11:12:41 spear kernel: traps: Media[441411] trap invalid opcode ip:5568ee586d58 sp:7fd91f5fa8f0 error:0 in brave[b226d58,5568e6598000+dbbe000]

**Comment by EERomeo** [comment]
Well, it's something with the Brave itself, after the last update last week, I noticed there is a new top right button on the top bar. Also, if I had a video playing in one workspace, if I changed the workspace the audio kept playing as it should, but if I switched back to the video workspace, the video was frozen, it was coming back only on focusing the Brave window. I downgraded to the previous version and it's back to working normal. No other problems for me but it's pretty clear it has something to do with Brave not Omarchy.
